#!/sbin/sh

# trigger blue LED
echo '255' > /sys/class/leds/blue/brightness
echo '0' > /sys/class/leds/red/brightness
echo '0' > /sys/class/leds/green/brightness

cat /dev/input/event2 > /dev/keycheck&
sleep 3

# trigger blue LED
echo '0' > /sys/class/leds/blue/brightness
echo '0' > /sys/class/leds/red/brightness
echo '0' > /sys/class/leds/green/brightness

kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
# fixing CPU clocks to avoid issues in recovery
echo 1017600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 249600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount -l /system
umount -l /data
umount -l /cache
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery 
fi

#continue booting

